name: Test Missing CloudFront Distribution

on:
  workflow_dispatch:

jobs:
  test-missing-cloudfront-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Static Sites Action without cloudfront-distribution
        uses: ./
        with:
          assume-role-arn: arn:aws:iam::123456789012:role/TestRole
          bucket-name: test-bucket
          working-directory: ./site
        continue-on-error: true

      - name: Mark job as success
        run: exit 0