name: Test Missing ARN

on:
  push:

jobs:
  test-missing-arn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Static Sites Action without ARN
        uses: UKHomeOffice/core-cloud-static-sites-action@CCL-763-testing
        with:
          bucket-name: test-bucket
          working-directory: ./site
          cloudfront-distribution: TESTDISTID