name: Test Missing Working Directory

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

jobs:
  test-missing-working-directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Static Sites Action without working-directory
        uses: ./
        with:
          assume-role-arn: arn:aws:iam::123456789012:role/TestRole
          bucket-name: test-bucket
          cloudfront-distribution: TESTDISTID