name: Test Invalid CloudFront Distribution

on:
  workflow_dispatch:

jobs:
  test-invalid-cloudfront-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Static Sites Action
        uses: ./
        with:
          assume-role-arn: arn:aws:iam::992382599151:role/cc-static-site-staticsite-elliotthrynacz-test-site
          bucket-name: cc-static-site-staticsite-elliotthrynacz-test-site
          working-directory: .github/workflows/tests/static-site
          cloudfront-distribution: INVALID123
        continue-on-error: true

      - name: Mark job as success
        run: exit 0